### ISSUE TITLE
金手指用不了

### ISSUE THREAD

**Issue by tchivs** [carcaschoi/ShallowSea#10]
在菜单里面下载的进入EdiZon里面显示没有找到该游戏的金手指，我自己下载的放atmosphere\contents目录也还是不行，试了好几个游戏还是不行。

**Comment by carcaschoi** [comment]
可以試一試用tesla menu開啓金手指🤔

**Comment by tchivs** [comment]
> 可以试一试用tesla menu打开金手指🤔

打开后还是没有可用的金手指，奇怪了

**Comment by carcaschoi** [comment]
會不會是遊戲版本不對金手指

**Comment by carcaschoi** [comment]
我剛剛測試了沒有問題呀，v1.7.6.2，是使用tesla menu開啟金手指
