### ISSUE TITLE
Just a quick question 

### ISSUE THREAD

**Issue by yanisdreemurr** [carcaschoi/ShallowSea#11]
I wanted to know which program would have to be removed in order to be able to access Nintendo's online server ? (yes I love to take risks, not judge) x)

**Comment by carcaschoi** [comment]
First, I dont recommend remove incognito and 90dns because it has a high risk to get ban

Delete [atmosphere/hosts] folder and exosphere.ini at the root of the sd card

& sorry for my poor English lol

**Comment by yanisdreemurr** [comment]
Do not worry, I understood perfectly, in any case thank you for your answer!
