### ISSUE TITLE
Change the Startup Screen

### ISSUE THREAD

**Issue by Movingtofu** [carcaschoi/ShallowSea#12]
Startup Screen wallpaper is beautiful , Can i change the startup screen and the logo by myself ?

**Comment by yanisdreemurr** [comment]
Yep, you just have to change the image to this root: 

F:\atmosphere\bootlogo.bmp

**Comment by carcaschoi** [comment]
https://gbatemp.net/threads/share-your-custom-atmosphere-fusee-secondary-bootlogos.532018/

**Comment by Movingtofu** [comment]
And i found a folder "sd:\atmosphere\exefs_patches\ShallowSea_logo" , how can i change the logo .ips ?

**Comment by carcaschoi** [comment]
the ips files are the bootlogo, not a start-up screen

**Comment by carcaschoi** [comment]
You can change it too

**Comment by yanisdreemurr** [comment]
> And i found a folder "sd:\atmosphere\exefs_patches\ShallowSea_logo" , how can i change the logo .ips ?

if you want to know how to change the logo .ips , I can advise you this video: https://www.sthetix.info/creating-custom-boot-logo-with-switch-logo-patcher/

**Comment by Movingtofu** [comment]
Thanks a lot
