### ISSUE TITLE
Suggestion: language support

### ISSUE THREAD

**Issue by bettydreemurr** [carcaschoi/ShallowSea#15]
why not make a different file like for example "README.md" (or for other file)  containing different languages? it will avoid seeing English with Chinese and it would be more readable I think x) 
 
 
![image](https://user-images.githubusercontent.com/46537034/119696688-bdbe6f00-be4f-11eb-8a66-35db2b8245de.png)

So a bit in this style as on the screen, and there the different people will be able to propose their translation
(I could do the translations in French and English, if you want to do that of course, it's just an suggestion xD)

**Comment by carcaschoi** [comment]
😍A good suggestion. I may do it after the exam😅

**Comment by camillomurcia** [comment]
Me interesa yo podría hacer la traducción a Español, quiero ayudar (Igualmente como sugerencia xD) pero que buena idea de @yanisdreemurr

**Comment by Pastel-Knight** [comment]
I can help with Arabic and french translations.

**Comment by yanisdreemurr** [comment]
Cool! well, I'll be able to start translating and create a pull request hehe

**Comment by carcaschoi** [comment]
You are welcome to pull request for the readme enhanced. I will close this issue because it is not link to the aio package bug
