### ISSUE TITLE
ldn_mitm

### ISSUE THREAD

**Issue by ray1025** [carcaschoi/ShallowSea#20]
1.There is a new version of ldn_mitm.
[https://github.com/spacemeowx2/ldn_mitm/suites/3211487306/artifacts/74290950](https://github.com/spacemeowx2/ldn_mitm/suites/3211487306/artifacts/74290950)
It works on my switch. Firmware: 12.1.0, AMS: 0.19.5.

2.In the AIO package, the name in toolbox.json of ldn_mitm is wrong.
[l] is [L], not [i].

thx~

**Comment by carcaschoi** [comment]
Thx, I will update it later

**Comment by carcaschoi** [comment]
Updated v1.8.4
