### ISSUE TITLE
Edizon is missing

### ISSUE THREAD

**Issue by CorruptedMinds** [carcaschoi/ShallowSea#27]
**ShallowSea version**
v2.4.3

**Describe the bug**
Edizon is missing from the zip file.

**To Reproduce**
1. ... Download ShallowSea-ams.zip
2. ... Unzip, there is no edizon folder or edizon nro

**Expected behavior**
Edizon folder existing in previous releases

**Additional context**
Looks like it was just forgotten to be added to the package

**Comment by carcaschoi** [comment]
You can use the tesla version of edizon ovl instead

**Comment by CorruptedMinds** [comment]
Okay, I will play around with it tomorrow. I noticed that OVLMenu isn't the newest release (1.1.4).
https://github.com/WerWolv/Tesla-Menu/tree/v1.1.4

It seems to be the prior version.
