### ISSUE TITLE
Problem about ShallowSea

### ISSUE THREAD

**Issue by philcheung007** [carcaschoi/ShallowSea#3]
Hi carcaschoi,

Can I check and confirm if there are any issues with the RCM loader files please. Just updated and RCM loader will not load into hekate and is stuck in a black screen? 

Thanks

**Comment by carcaschoi** [comment]
You need to extract ShallowSea package first because rcmloader(blue light) is payload forwarder that autolaunch microsd:/payload.bin . If the file is not existed, it will stuck in a black screen

And I am sorry for my poor English, feel free to contact me with Chinese or English

**Comment by philcheung007** [comment]
Hi carcaschoi,

Thanks for coming back so quickly. Do I extract and replace the SD card with "ShallowSea-ams"?

**Comment by carcaschoi** [comment]
Please follow the user guide to update(change) Shallowsea package
https://github.com/carcaschoi/ShallowSea/blob/main/User%20guide.md

**Comment by carcaschoi** [comment]
You should not just copy and paste the ShallowSea content directly. It is recommended that delete some files inside the sd card (follow Shallowsea user guide) to avoid error

**Comment by philcheung007** [comment]
Followed the steps and getting this:

A fatal error occurred when running Atmosphere.

![IMG_1623](https://user-images.githubusercontent.com/80692743/111164956-6de14300-8596-11eb-9b73-baa3fa895c97.jpg)

**Comment by carcaschoi** [comment]
🤔Do you follow this https://github.com/carcaschoi/ShallowSea/blob/main/User%20guide.md#%E5%A4%A7%E6%B0%A3%E5%B1%A4%E6%9B%B4%E6%96%B0%E6%95%B4%E5%90%88%E5%8C%85%E6%8C%87%E5%8D%97-atmosphere-update-aio-package-guide

**Comment by carcaschoi** [comment]
Would u like to send me a photo to show me the contents in the ad card root？

**Comment by philcheung007** [comment]
![IMG_1625](https://user-images.githubusercontent.com/80692743/111166441-00361680-8598-11eb-8a9c-475b04758281.jpg)

Yes - I followed the steps, deleted and kept the suggested folders. Then copied the two files over. 

Attached is the screenshot, thanks

**Comment by carcaschoi** [comment]
![IMG_20210315_222957](https://user-images.githubusercontent.com/64573431/111169850-4e6e0880-85de-11eb-9176-c259074fd9a5.jpg)
Delete the folder and file that I have highlighted and extract Shallowsea-ams.rar & switch English extra package.rar one more time

**Comment by philcheung007** [comment]
Tried again and getting the same error.

Any other suggestions.

![IMG_1626](https://user-images.githubusercontent.com/80692743/111178953-83a93500-85a3-11eb-9282-bf0b5d2423ea.jpg)

**Comment by philcheung007** [comment]
Asking on FB groups and they suggested deleting the folder but now getting this error.

![IMG_1627](https://user-images.githubusercontent.com/80692743/111203612-24581e80-85bd-11eb-906f-8cb169fe85b0.jpg)

**Comment by carcaschoi** [comment]
Do you install themes before？you should delete 「atmosphere/contents/0100000000001000」& 「atmosphere/titles/0100000000001000

**Comment by philcheung007** [comment]
This was the SD card before trying to update. I had someone do it for me and there is a themes folder.

![IMG_1616](https://user-images.githubusercontent.com/80692743/111284351-f532c300-8637-11eb-85a6-c96121c352dd.jpg)

Just loaded the SD card and those two folders are not there.

![Contents folder](https://user-images.githubusercontent.com/80692743/111284483-11cefb00-8638-11eb-9048-12809cecfab5.jpg)

![Title](https://user-images.githubusercontent.com/80692743/111284564-214e4400-8638-11eb-9f3f-d149e164eb9e.jpg)

**Comment by carcaschoi** [comment]
I have no idea with this issue😥

**Comment by carcaschoi** [comment]
If you don't mind，you can use JKSV to dump game save and clean all the contents in the sd card except JKSV folder. Then redo the emuMMC again

**Comment by philcheung007** [comment]
Sorry - I had the original version installed for me and not sure what to do now.

Do you have a guide to dump save and emuMMC. There are a lot of different sites online but have different steps.

Thanks for your time and help. Appreciate it.

**Comment by carcaschoi** [comment]
How to use JKSV:
1. extract jksv.nro to the 「switch」folder
2. open jksv app in the album
3. press Y to dump all games save
4. After it finished, The 「JKSV」folder will be created and dont delete it because it contains user game save

**Comment by philcheung007** [comment]
Was trying to follow this page but on the switch, I cannot get into the HomeBrew screen.

https://projectpokemon.org/home/tutorials/save-editing/managing-switch-saves/using-jksv-r88/

Tried to attach a video but it's too large. Basically when it starts up, it gets stuck on the black screen.

**Comment by carcaschoi** [comment]
Delete all the folder except 「emuMMC」 folder，Then extract ShallowSea aio package

**Comment by philcheung007** [comment]
Still not working.

Have raised this:
https://github.com/Atmosphere-NX/Atmosphere/issues/1403

**Comment by carcaschoi** [comment]
I do not recommend to send the issue to atmosphere-nx because my aio package is using neutos kernel and come with sigpatch. sciresM may say 「piracy is not support」then close the issue, you can try to use clean atmosphere kernel (without sigpatch) to see there are any issue

**Comment by philcheung007** [comment]
Was watching a clip on youtube for updating; do I have to turn on "Update Reboot 2 Payload" in hekate.

Tried to download Atmosphere and override the files but getting this error now.

![IMG_1654](https://user-images.githubusercontent.com/80692743/111513062-4fbb4480-8748-11eb-8773-1b0babb1ead5.jpg)

**Comment by carcaschoi** [comment]
https://github.com/Atmosphere-NX/Atmosphere/issues/1120

**Comment by carcaschoi** [comment]
Delete the folder it has mentioned in atmosphere/contents

**Comment by philcheung007** [comment]
Strange I don't see that folder in the list.

![Contents](https://user-images.githubusercontent.com/80692743/111654944-1d215280-8801-11eb-970e-3392144fdebb.jpg)

**Comment by philcheung007** [comment]
Hi - was wondering if you can help me. Restarted with fresh emuMMC and it's working but I cannot get Tinfoil working. It's just spinning when trying to load. Any idea how to fix this, thanks 

![162915294_4359673974062308_5459017374384051493_n](https://user-images.githubusercontent.com/80692743/111878146-cfdae780-899e-11eb-8f5f-8565040c5755.jpg)

**Comment by carcaschoi** [comment]
run tinfoil installer

**Comment by philcheung007** [comment]
Tried deleting and updating.
Updated sigpatches.
Used cling-wrap.
But it’s still not loading.

**Comment by philcheung007** [comment]
Used the previous shallowsea package and it worked. Thanks 
Having issues with the new shallowsea one.

**Comment by carcaschoi** [comment]
ok , I will have a look with v1.5.6

**Comment by carcaschoi** [comment]
對了，你可以試一試最新版本ShallowSea v1.5.7😏
