### ISSUE TITLE
After updated 13.2.0 , some games can't open

### ISSUE THREAD

**Issue by Movingtofu** [carcaschoi/ShallowSea#31]
it keeps reminding me the game need to be update, but the game already latest version , and "Heave Ho" game can't open

**Comment by carcaschoi** [comment]
try to update the game via tinfoil？

**Comment by Movingtofu** [comment]
Yes, I used 13.0.0 before and I formated the SD card , and installed 13.2.0, and redownload all the games via tinfoil, but some of the game keeps reminding me they to be updated, but the game is already the latest version

**Comment by Saharsha1999** [comment]
> try to update the game via tinfoil？

Hey, any possibility I can contact you? Got my switch with your Shallow Sea running. Had some doubts? I hope you can help me. Thanks @carcaschoi

**Comment by carcaschoi** [comment]
> Yes, I used 13.0.0 before and I formated the SD card , and installed 13.2.0, and redownload all the games via tinfoil, but some of the game keeps reminding me they to be updated, but the game is already the latest version

Let me have a test on it later

**Comment by Movingtofu** [comment]
I found a solution, when downloading the game via tinfoil, it needs to be ticked on " reinstall NCA "

**Comment by leafleave** [comment]
maybe try reset required version using DBI?
