### ISSUE TITLE
pls update hekate to latest version

### ISSUE THREAD

**Issue by elantion** [carcaschoi/ShallowSea#35]
**ShallowSea version**
2.11.0

**Describe the bug**
Can not boot with default files.

**To Reproduce**
1. copy all files into sd card.
2. boot it by TegraRcm gui

**Expected behavior**
boot success

**Desktop that you copy file to switch sd card (window/macos/linux) :**
windows 11

**Additional context**
It seem like this version using hekate 5.5 and it comes to somthing uncompatible with my micro sd card. It boot failed. After I update to 5.7, it works perfectly.
So, may I suggest to update hekate to fix this issue? Many thanks!

**Comment by carcaschoi** [comment]
ok, I will fix it in the next update
