### ISSUE TITLE
black shop don't work , is it server already down ??

### ISSUE THREAD

**Issue by Movingtofu** [carcaschoi/ShallowSea#37]
is it server already down ?? , i can't find any game

**Comment by carcaschoi** [comment]
sometimes yes

**Comment by leafleave** [comment]
Almost every server down, but you can try [https://games.jits.cc/account#](this link)(English), or this link(https://www.91tvg.com/forum.php?mod=viewthread&tid=298077)（中文）to use your own gdrive as a proxy to download.
