### ISSUE TITLE
无法连接网络

### ISSUE THREAD

**Issue by mizuka-wu** [carcaschoi/ShallowSea#4]
网络无法连接了，即使连上路由器也显示网络服务超时

**Comment by carcaschoi** [comment]
應該是路由器問題吧

**Comment by carcaschoi** [comment]
如果你是說連接任天堂網絡服務失敗的話是正常的，因為我屏蔽了任天堂的所有連接

**Comment by mizuka-wu** [comment]
普通路由 手机4g都不行
硬破机器 联网显示服务器超时

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: carcaschoi ***@***.***>
发送时间: Thursday, March 25, 2021 12:59:24 PM
收件人: carcaschoi/ShallowSea ***@***.***>
抄送: Edward Mizuka ***@***.***>; Author ***@***.***>
主题: Re: [carcaschoi/ShallowSea] 无法连接网络 (#4)


是路由器}吧

―

**Comment by carcaschoi** [comment]
是不是國行機器？

**Comment by carcaschoi** [comment]
是的話就要刪除atmosphere/hosts/default.txt，國行機器好像不能用90dns

**Comment by mizuka-wu** [comment]
感谢

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: carcaschoi ***@***.***>
发送时间: Thursday, March 25, 2021 1:06:38 PM
收件人: carcaschoi/ShallowSea ***@***.***>
抄送: Edward Mizuka ***@***.***>; Author ***@***.***>
主题: Re: [carcaschoi/ShallowSea] 无法连接网络 (#4)


是的就要h除atmosphere/hosts/default.txt，C器好像不能用90dns

―

**Comment by carcaschoi** [comment]
我剛才test了一下，發現是host配置問題，已經更新修復， 你可以選擇下載v1.5.7(3) 或者 v1.6.0(1)

**Comment by mizuka-wu** [comment]
好的 我直接替换default.host试试

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: carcaschoi ***@***.***>
发送时间: Friday, March 26, 2021 7:29:49 PM
收件人: carcaschoi/ShallowSea ***@***.***>
抄送: Edward Mizuka ***@***.***>; Author ***@***.***>
主题: Re: [carcaschoi/ShallowSea] 无法连接网络 (#4)


我才test了一下，lF是host配置}，已更新修停 你可以x裣螺dv1.5.7(3) 或者 v1.6.0(1)

―
