### ISSUE TITLE
v2.12.2 金手指问题

### ISSUE THREAD

**Issue by zinc357** [carcaschoi/ShallowSea#40]
**ShallowSea version**
What is the version of ShallowSea you download?
[v2.12.2](https://github.com/carcaschoi/ShallowSea/releases/tag/v2.12.2)
**Describe the bug**
tesla菜单选择cheat后，无反应，之后无法再唤起tesla菜单

**Comment by carcaschoi** [comment]
try try v2.12.3

**Comment by carcaschoi** [comment]
v2.12.4 should fix this problem
