### ISSUE TITLE
Error code: 2162-0002 (0x4a2)

### ISSUE THREAD

**Issue by philcheung007** [carcaschoi/ShallowSea#41]
![97682676-0174-474D-842F-16C4E9471198](https://user-images.githubusercontent.com/80692743/209024383-d6e784bc-293a-432b-bd7d-67fd273f6307.jpeg)
**ShallowSea version**
What is the version of ShallowSea you download?
Trying to use the update function 1

**Describe the bug**
A clear and concise description of what the bug is, you are recommended to upload photos or youtube video link.

**To Reproduce**
1.  Updating using 1
2. ...

**Expected behavior**

**Desktop that you copy file to switch sd card (window/macos/linux) :**

**Additional context**

**Comment by philcheung007** [comment]
Searching online and people suggest themes issue?

**Comment by carcaschoi** [comment]
the theme should be deleted during auto update process. Is it the emuMMC issue? You may try to rebuild a new one
