### ISSUE TITLE
hekate toolbox is not working 

### ISSUE THREAD

**Issue by SrPhreaK** [carcaschoi/ShallowSea#42]
**ShallowSea version**
What is the version of ShallowSea you download?
**the most recent
I deleted everything except the nintendo and emummc folders.
I put the shallowsea package on the card.**

**Describe the bug**
**either in applet mode or without applet mode when i try to use the hekate toolbox i get an error message running or atmosphere error .
I even tried to replace it with the latest homebrew "nro" on github, but it made no difference.**

**Desktop that you copy file to switch sd card (window/macos/linux) :**
**windows 10**

**Comment by SrPhreaK** [comment]
and just wanting to help , taking advantage and giving two suggestions :

I recommend editing a better image for the shallowsea toolbox .
it may still be the same , just better framed .

and here in Brazil the best package uses these launch options:
1- AMS ( EMUNAND+INCOGNITO )
(only those who have emunand can enter)
2- AMS ( SYSMMC+INCOGNITO )
3- AMS ( SYSMMC )
4- OFFICIAL FIRMWARE

**Comment by carcaschoi** [comment]
> **ShallowSea version** What is the version of ShallowSea you download? **the most recent I deleted everything except the nintendo and emummc folders. I put the shallowsea package on the card.**
> 
> **Describe the bug** **either in applet mode or without applet mode when i try to use the hekate toolbox i get an error message running or atmosphere error . I even tried to replace it with the latest homebrew "nro" on github, but it made no difference.**
> 
> **Desktop that you copy file to switch sd card (window/macos/linux) :** **windows 10**

It is strange that I can run hekatetoolbox v4.0.2 on my mariko switch.

**Comment by carcaschoi** [comment]
> and just wanting to help , taking advantage and giving two suggestions :
> 
> I recommend editing a better image for the shallowsea toolbox . it may still be the same , just better framed .
> 
> and here in Brazil the best package uses these launch options: 1- AMS ( EMUNAND+INCOGNITO ) (only those who have emunand can enter) 2- AMS ( SYSMMC+INCOGNITO ) 3- AMS ( SYSMMC ) 4- OFFICIAL FIRMWARE

Actually, I really hate people booting ams(sysmmc) without 90dns or incognito.
Their switch will easily get ban if they install tinfoil, which is included in my package, and go online.
Therefore, for safety reason, I am not going to set a lot of sysmmc launch options in the hekate.

Btw, thanks for ur suggestions
