### ISSUE TITLE
Cannot read cartidges, even put the autonogc off

### ISSUE THREAD

**Issue by al10capote** [carcaschoi/ShallowSea#45]
**ShallowSea version**
What is the version of ShallowSea you download?

**Describe the bug**
A clear and concise description of what the bug is, you are recommended to upload photos or youtube video link.

**To Reproduce**
1. ...
2. ...

**Expected behavior**

**Desktop that you copy file to switch sd card (window/macos/linux) :**

**Additional context**

**Comment by al10capote** [comment]
I already has swallowsea 2.16.0

**Comment by carcaschoi** [comment]
try to update both systems to the latest HOS version

**Comment by al10capote** [comment]
I am on sys 15.0.1, with the last sawallowsea update

**Comment by carcaschoi** [comment]
Update sysnand to 16.0.2
