### ISSUE TITLE
How do I change the hotkey to callout telsa memu?

### ISSUE THREAD

**Issue by elcoer** [carcaschoi/ShallowSea#46]
Hi There!Thank you for your greatwork!
How do I change the defult tesla hotkey  : L+↓ +R stick ?
I want change it to L+R,but I don't konw how to do it.

**Comment by bao3** [comment]
The hotkey is defined by  Tesla overlay, perhaps you could try to modify it in that code.

**Comment by elcoer** [comment]
OK Thks
