### ISSUE TITLE
打开游戏后报错

### ISSUE THREAD

**Issue by feiyangjun-1** [carcaschoi/ShallowSea#48]
**ShallowSea version**
v2.18.0

**Describe the bug**
使用 v2.18.0 打开游戏后报错，无法进入

**To Reproduce**
1. 将下载的压缩包解压至 SD 卡根目录
2. 启动设备，进入 EmuMMC
3. 打开游戏，提示无法打开软件

**Expected behavior**
游戏被正常打开

**Desktop that you copy file to switch sd card (window/macos/linux) :**
Windows11

**Additional context**
将我自己制作的 sigpatch 放进 SD 卡后就可以打开了
https://github.com/feiyangjun-1/ns-sigpatches/releases/tag/v1.0

**Comment by carcaschoi** [comment]
okk hotfixed
