### ISSUE TITLE
Update Atmosphere 19.2

### ISSUE THREAD

**Issue by yanisdreemurr** [carcaschoi/ShallowSea#9]
0.19.2 is Atmosphère's forty-eighth official release.

fusee-primary was last updated in: 0.19.2.

With thanks to the @switchbrew team, Atmosphère 0.19.2 is bundled with hbl 2.4.1, and hbmenu 3.4.0.

The following was changed since the last release:

Atmosphère's components were further updated to reflect latest official behaviors as of 12.0.0.
Notably, erpt was updated to implement the new forced shutdown detection feature.
When a forced-shutdown occurs, an erpt_report will be generated and saved to the SD card on the next boot.
Atmosphere-libs was updated to use GCC 11 (latest devkitA64/devkitARM releases).
Initial inspections show mild-to-moderate optimizer improvements in several important places (kernel is 0x3000 smaller).
General system stability improvements to enhance the user's experience.
A number of minor issues were fixed, including:
A bug was fixed that caused a black screen when attempting to boot firmware versions 2.0.0-4.1.0.
A bug was fixed that caused sm to abort when at the session limit, rather than returning error codes.
A bug was fixed that allowed for resource exhaustion on 12.0.0, under certain circumstances.
Several issues were fixed, and usability and stability were improved.

https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.19.2

**Comment by carcaschoi** [comment]
you guys don't have to send a issue every time when atmosphere updated. I received a email when atmosphere updated. I just wake up🤣. I will update it at soon as possible

**Comment by carcaschoi** [comment]
Updated v1.7.5

**Comment by yanisdreemurr** [comment]
Oh excuse me, I'm just trying to help my way haha

**Comment by carcaschoi** [comment]
👍，If you find some interesting or helpful homebrew app, you can ask me to add them😁
